# Generated by Django 4.2.7 on 2025-12-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="store_logos/"),
        ),
    ]
