# Generated by Django 4.2.7 on 2026-01-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='maps_photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of your store location/map', null=True, upload_to='store_maps/'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='Upload your Payment QR Code', null=True, upload_to='payment_qrs/'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(blank=True, help_text='e.g., Clothing, Electronics, Grocery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='e.g., +9779812345678', max_length=20, null=True),
        ),
    ]
