# Generated by Django 4.2.7 on 2026-01-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_store_description_store_google_maps_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Public URL for logo (if not uploaded)', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='maps_photo_url',
            field=models.URLField(blank=True, help_text='Public URL for Map Photo', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_qr_url',
            field=models.URLField(blank=True, help_text='Public URL for Payment QR', null=True),
        ),
    ]
